#!/bin/sh
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2013 Wang Diancheng

if [ $# -eq 0 ]
then
    echo "usage: $0 transaction-rate.log [out.png]"
    echo "reading transaction-rate.log file to plot transaction rate"
    exit 1
fi

datafile=$1
if [ ! -r "$datafile" ]
then
	echo "could not read transaction rate data file \"$datafile\""
	exit 1
fi

# if 2 arguments given output a PNG picture.
term=
outfile=$2
if [ -n "$outfile" ]
then
    term="set term png size 800,600;set output '$outfile'"
fi

/usr/bin/gnuplot <<EOF
$term
datafile='$datafile'
set grid
set title "Transaction Rate"
set ylabel "Transactions per Minute"
set xlabel "Elapsed Time (seconds)"
plot datafile using 1:2 w l title "Delivey", datafile u 1:3 w l title "New Order", datafile using 1:4 w l title "Order Status", datafile u 1:5 w l title "Payment", datafile u 1:6 w l title "Stock Level"
pause mouse
EOF
